"""income bonus + goal monthly contribution

Revision ID: 397a73cf3475
Revises: 3cff394a396b
Create Date: 2026-06-05 01:28:36.607322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397a73cf3475'
down_revision: Union[str, None] = '3cff394a396b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add monthly_contribution with a temporary server_default to backfill any
    # existing rows, then drop the default so the schema matches the ORM model.
    # (The new IncomeCategory 'bonus' value needs no DDL: native_enum=False
    # stores the column as VARCHAR with no CHECK constraint.)
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('monthly_contribution', sa.Numeric(precision=14, scale=2),
                      nullable=False, server_default='0')
        )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('monthly_contribution', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('monthly_contribution')

    # ### end Alembic commands ###
