"""expense cashback fields

Revision ID: 3cff394a396b
Revises: dacdfcc54fa9
Create Date: 2026-06-05 01:08:33.060736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cff394a396b'
down_revision: Union[str, None] = 'dacdfcc54fa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add the new columns. NOT NULL columns get a temporary server_default so
    # any pre-existing rows are backfilled safely.
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_online', sa.Boolean(), nullable=False,
                      server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('cashback_eligible', sa.Boolean(), nullable=False,
                      server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('cashback_amount', sa.Numeric(precision=12, scale=2),
                      nullable=False, server_default='0')
        )
        batch_op.add_column(
            sa.Column('cashback_type',
                      sa.Enum('CASHBACK', 'POINTS', 'MILES', 'NONE',
                              name='cardrewardtype', native_enum=False, length=20),
                      nullable=True)
        )
        batch_op.add_column(sa.Column('cashback_rule', sa.String(length=60), nullable=True))

    # Drop the temporary server defaults so the DB schema matches the ORM models
    # (which use application-level defaults only).
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('is_online', server_default=None)
        batch_op.alter_column('cashback_eligible', server_default=None)
        batch_op.alter_column('cashback_amount', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('cashback_rule')
        batch_op.drop_column('cashback_type')
        batch_op.drop_column('cashback_amount')
        batch_op.drop_column('cashback_eligible')
        batch_op.drop_column('is_online')

    # ### end Alembic commands ###
