"""initial schema

Revision ID: dacdfcc54fa9
Revises: 
Create Date: 2026-06-05 00:51:37.138055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacdfcc54fa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'GROCERIES', 'TRANSPORT', 'SHOPPING', 'ENTERTAINMENT', 'UTILITIES', 'RENT', 'HEALTH', 'EDUCATION', 'TRAVEL', 'INSURANCE', 'INVESTMENT', 'EMI', 'SUBSCRIPTION', 'PERSONAL_CARE', 'GIFTS', 'TAXES', 'FEES', 'OTHER', name='expensecategory', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period', sa.Enum('WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod', native_enum=False, length=20), nullable=False),
    sa.Column('spent', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=120), nullable=False),
    sa.Column('issuer', sa.String(length=80), nullable=False),
    sa.Column('network', sa.Enum('VISA', 'MASTERCARD', 'RUPAY', 'AMEX', 'DINERS', 'OTHER', name='cardnetwork', native_enum=False, length=20), nullable=False),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('annual_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reward_type', sa.Enum('CASHBACK', 'POINTS', 'MILES', 'NONE', name='cardrewardtype', native_enum=False, length=20), nullable=False),
    sa.Column('reward_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('valid_thru', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_cards_user_id'), ['user_id'], unique=False)

    op.create_table('emis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_name', sa.String(length=120), nullable=False),
    sa.Column('loan_type', sa.Enum('HOME', 'CAR', 'PERSONAL', 'EDUCATION', 'BUSINESS', 'GOLD', 'CREDIT_CARD', 'OTHER', name='loantype', native_enum=False, length=20), nullable=False),
    sa.Column('lender', sa.String(length=80), nullable=True),
    sa.Column('principal_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('emi_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('months_paid', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('total_payable', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emis_next_due_date'), ['next_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_emis_user_id'), ['user_id'], unique=False)

    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('EMERGENCY_FUND', 'VACATION', 'HOME', 'CAR', 'EDUCATION', 'WEDDING', 'GADGET', 'RETIREMENT', 'INVESTMENT', 'OTHER', name='goalcategory', native_enum=False, length=20), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority', native_enum=False, length=10), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'ABANDONED', name='goalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'FREELANCE', 'BUSINESS', 'RENTAL', 'INTEREST', 'DIVIDEND', 'CAPITAL_GAINS', 'GIFT', 'REFUND', 'OTHER', name='incomecategory', native_enum=False, length=20), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='frequency', native_enum=False, length=20), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_income_received_date'), ['received_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_income_user_id'), ['user_id'], unique=False)

    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('investment_type', sa.Enum('STOCKS', 'MUTUAL_FUNDS', 'ETF', 'FIXED_DEPOSIT', 'RECURRING_DEPOSIT', 'PPF', 'EPF', 'NPS', 'BONDS', 'GOLD', 'REAL_ESTATE', 'CRYPTO', 'OTHER', name='investmenttype', native_enum=False, length=20), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('symbol', sa.String(length=40), nullable=True),
    sa.Column('invested_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('avg_buy_price', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('interest_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investments_user_id'), ['user_id'], unique=False)

    op.create_table('monthly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_expense', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_savings', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_investment', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('net_cashflow', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('top_category', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_summary_user_period')
    )
    with op.batch_alter_table('monthly_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_summary_user_id'), ['user_id'], unique=False)

    op.create_table('net_worth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_worth', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('investments_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('property_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_assets', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('credit_card_debt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('loans_debt', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('other_liabilities', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'snapshot_date', name='uq_networth_user_date')
    )
    with op.batch_alter_table('net_worth', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_net_worth_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_net_worth_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ALERT', 'REMINDER', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('category', sa.Enum('BILL', 'BUDGET', 'GOAL', 'EMI', 'SUBSCRIPTION', 'CREDIT_CARD', 'INVESTMENT', 'INSIGHT', 'SYSTEM', name='notificationcategory', native_enum=False, length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('related_entity_type', sa.String(length=40), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('STREAMING', 'MUSIC', 'SOFTWARE', 'CLOUD', 'NEWS', 'FITNESS', 'GAMING', 'UTILITIES', 'EDUCATION', 'OTHER', name='subscriptioncategory', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_cycle', sa.Enum('ONE_TIME', 'DAILY', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY', name='frequency', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('next_billing_date', sa.Date(), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'DEBIT_CARD', 'CREDIT_CARD', 'NET_BANKING', 'WALLET', 'AUTO_DEBIT', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('reminder_days', sa.Integer(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_next_billing_date'), ['next_billing_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credit_card_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.Enum('FOOD', 'GROCERIES', 'TRANSPORT', 'SHOPPING', 'ENTERTAINMENT', 'UTILITIES', 'RENT', 'HEALTH', 'EDUCATION', 'TRAVEL', 'INSURANCE', 'INVESTMENT', 'EMI', 'SUBSCRIPTION', 'PERSONAL_CARE', 'GIFTS', 'TAXES', 'FEES', 'OTHER', name='expensecategory', native_enum=False, length=20), nullable=False),
    sa.Column('subcategory', sa.String(length=60), nullable=True),
    sa.Column('merchant', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'UPI', 'DEBIT_CARD', 'CREDIT_CARD', 'NET_BANKING', 'WALLET', 'AUTO_DEBIT', 'OTHER', name='paymentmethod', native_enum=False, length=20), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_ai_categorized', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['credit_card_id'], ['credit_cards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_credit_card_id'), ['credit_card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_transaction_date'), ['transaction_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_expenses_credit_card_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_billing_date'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))

    op.drop_table('notifications')
    with op.batch_alter_table('net_worth', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_net_worth_user_id'))
        batch_op.drop_index(batch_op.f('ix_net_worth_snapshot_date'))

    op.drop_table('net_worth')
    with op.batch_alter_table('monthly_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_summary_user_id'))

    op.drop_table('monthly_summary')
    with op.batch_alter_table('investments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investments_user_id'))

    op.drop_table('investments')
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_income_user_id'))
        batch_op.drop_index(batch_op.f('ix_income_received_date'))

    op.drop_table('income')
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    op.drop_table('goals')
    with op.batch_alter_table('emis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emis_user_id'))
        batch_op.drop_index(batch_op.f('ix_emis_next_due_date'))

    op.drop_table('emis')
    with op.batch_alter_table('credit_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_cards_user_id'))

    op.drop_table('credit_cards')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))

    op.drop_table('budgets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
